drm/amdgpu: fix build error
Regression by patch:
fd583c4f01a7 drm/amdgpu: drop duplicated ecc check for vega10 (v4)

CC [M]  drivers/gpu/drm/amd/amdgpu/gfxhub_v2_1.o
drivers/gpu/drm/amd/amdgpu/gmc_v9_0.c: In function ‘gmc_v9_0_late_init’:
drivers/gpu/drm/amd/amdgpu/gmc_v9_0.c:1216:59: error: expected ‘)’ before ‘{’ token
 1216 |   if (!(adev->ras_features & (1 << AMDGPU_RAS_BLOCK__UMC)) {
      |      ~                                                    ^~
      |                                                           )
drivers/gpu/drm/amd/amdgpu/gmc_v9_0.c:1220:2: error: expected expression before ‘}’ token
 1220 |  }
      |  ^
  CC [M]  drivers/gpu/drm/amd/amdgpu/umc_v6_1.o

Signed-off-by: Guchun Chen <guchun.chen@amd.com>
Reviewed-by: Hawking Zhang <Hawking.Zhang@amd.com>